{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
    app: {{ template "traefik.fullname" . }}
    chart: {{ template "traefik.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.vault.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.vault.size | quote }}
  {{ include "traefik.storageClass" . }}
{{- end -}}
